=== Subash3002/Api_Fbb_RestAssured/src/main/resources/consignmentSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "addedProducts": {
      "type": "array",
      "items": {}
    },
    "currentWarehouseTab": {
      "type": "integer"
    },
    "deliveryNotes": {
      "type": "null"
    },
    "draftNumber": {
      "type": "null"
    },
    "draftStatus": {
      "type": "string"
    },
    "merchantCode": {
      "type": "string"
    },
    "merchantName": {
      "type": "string"
    },
    "notAllocatedProducts": {
      "type": "array",
      "items": {}
    },
    "notEligibleInAnyWarehouse": {
      "type": "array",
      "items": {}
    },
    "newNotEligibleInAnyWarehouse": {
      "type": "array",
      "items": {}
    },
    "potentialInboundFee": {
      "type": "null"
    },
    "regionCode": {
      "type": "string"
    },
    "regionName": {
      "type": "string"
    },
    "removedProducts": {
      "type": "array",
      "items": {}
    },
    "selectedProducts": {
      "type": "object",
      "properties": {
        "FBB-60021-03209-00001": {
          "type": "object",
          "properties": {
            "blibliSku": {
              "type": "string"
            },
            "categoryHierarchy": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            },
            "categoryName": {
              "type": "string"
            },
            "confirmedQuantity": {
              "type": "null"
            },
            "itemCode": {
              "type": "string"
            },
            "itemName": {
              "type": "string"
            },
            "packageWeight": {
              "type": "number"
            },
            "productItemHeight": {
              "type": "number"
            },
            "productItemLength": {
              "type": "number"
            },
            "productItemWidth": {
              "type": "number"
            },
            "proposedQuantity": {
              "type": "integer"
            },
            "recommendedQuantity": {
              "type": "null"
            },
            "recommendedQuantityErrorCode": {
              "type": "null"
            }
          },
          "required": [
            "blibliSku",
            "categoryHierarchy",
            "categoryName",
            "confirmedQuantity",
            "itemCode",
            "itemName",
            "packageWeight",
            "productItemHeight",
            "productItemLength",
            "productItemWidth",
            "proposedQuantity",
            "recommendedQuantity",
            "recommendedQuantityErrorCode"
          ]
        }
      },
      "required": [
        "FBB-60021-03209-00001"
      ]
    },
    "shippingDetails": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "emergencyContactEmail": {
              "type": "string"
            },
            "emergencyContactNumber": {
              "type": "string"
            },
            "pickupPointAddress": {
              "type": "string"
            },
            "pickupPointCode": {
              "type": "string"
            },
            "pickupPointName": {
              "type": "string"
            },
            "preferredTimeSchedules": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "preferredDate": {
                      "type": "string"
                    },
                    "preferredTime": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "preferredDate",
                    "preferredTime"
                  ]
                }
              ]
            },
            "sellerPicName": {
              "type": "string"
            },
            "sellerPicPhoneNumber": {
              "type": "string"
            },
            "shippingType": {
              "type": "string"
            },
            "warehouseCode": {
              "type": "string"
            },
            "warehouseName": {
              "type": "string"
            },
            "warehouseAddress": {
              "type": "string"
            }
          },
          "required": [
            "emergencyContactEmail",
            "emergencyContactNumber",
            "pickupPointAddress",
            "pickupPointCode",
            "pickupPointName",
            "preferredTimeSchedules",
            "sellerPicName",
            "sellerPicPhoneNumber",
            "shippingType",
            "warehouseCode",
            "warehouseName",
            "warehouseAddress"
          ]
        }
      ]
    },
    "userType": {
      "type": "string"
    },
    "warehouseAllocations": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "selectedProducts": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "warehouseAddress": {
              "type": "string"
            },
            "warehouseCode": {
              "type": "string"
            },
            "warehouseName": {
              "type": "string"
            },
            "warehouseRank": {
              "type": "integer"
            }
          },
          "required": [
            "selectedProducts",
            "warehouseAddress",
            "warehouseCode",
            "warehouseName",
            "warehouseRank"
          ]
        }
      ]
    }
  },
  "required": [
    "addedProducts",
    "currentWarehouseTab",
    "deliveryNotes",
    "draftNumber",
    "draftStatus",
    "merchantCode",
    "merchantName",
    "notAllocatedProducts",
    "notEligibleInAnyWarehouse",
    "newNotEligibleInAnyWarehouse",
    "potentialInboundFee",
    "regionCode",
    "regionName",
    "removedProducts",
    "selectedProducts",
    "shippingDetails",
    "userType",
    "warehouseAllocations"
  ]
}

=== Subash3002/Api_Fbb_RestAssured/src/main/resources/consignment.json
{

  "addedProducts": [

  ],

  "currentWarehouseTab": 0,

  "deliveryNotes": null,

  "draftNumber": null,

  "draftStatus": "SELECT_SHIPMENT",

  "merchantCode": "BLF-60033",

  "merchantName": "BLF-60033",

  "notAllocatedProducts": [

  ],

  "notEligibleInAnyWarehouse": [

  ],

  "newNotEligibleInAnyWarehouse": [

  ],

  "potentialInboundFee": null,

  "regionCode": "BAN-001",

  "regionName": "West Java",

  "removedProducts": [

  ],

  "selectedProducts": {

    "FBB-60021-03209-00001": {

      "blibliSku": "BLF-60033-00001-00001",

      "categoryHierarchy": [

        "AN-1000028",

        "HA-1000067",

        "HA-1000066"

      ],

      "categoryName": "Android",

      "confirmedQuantity": null,

      "itemCode": "MTA-5429234-00001",

      "itemName": "testing FBB New Product CC BLACK",

      "packageWeight": 0.1,

      "productItemHeight": 30.0,

      "productItemLength": 30.0,

      "productItemWidth": 20.0,

      "proposedQuantity": 1,

      "recommendedQuantity": null,

      "recommendedQuantityErrorCode": null

    }

  },

  "shippingDetails": [

    {

      "emergencyContactEmail": "sakthi@gmail.com",

      "emergencyContactNumber": "4998158156",

      "pickupPointAddress": "",

      "pickupPointCode": "",

      "pickupPointName": "",

      "preferredTimeSchedules": [

        {

          "preferredDate": "2024-07-11T01:16:25.474Z",

          "preferredTime": "09:25"

        }

      ],

      "sellerPicName": "sakthi.samyuktha@gdn-commerce.com",

      "sellerPicPhoneNumber": "9012732163",

      "shippingType": "SHIPPED_BY_MERCHANT",

      "warehouseCode": "HUB-0000000001",

      "warehouseName": "BDG E - Bandung Kiaracondong",

      "warehouseAddress": "Jl. Ibrahim Adjie No.338, Kelurahan Binong, Kecamatan Batununggal, Kota Bandung Kel. Cisaranten Wetan, Kec. Cinambo, Kota Bandung"

    }

  ],

  "userType": "INTERNAL",

  "warehouseAllocations": [

    {

      "selectedProducts": [

        "BLF-60033-00001-00001"

      ],

      "warehouseAddress": "Jl. Ibrahim Adjie No.338, Kelurahan Binong, Kecamatan Batununggal, Kota Bandung Kel. Cisaranten Wetan, Kec. Cinambo, Kota Bandung",

      "warehouseCode": "HUB-0000000001",

      "warehouseName": "BDG E - Bandung Kiaracondong",

      "warehouseRank": 1

    }

  ]

}
